# Generated by Django 4.0.5 on 2022-07-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='icon',
            field=models.CharField(blank=True, default='fa-solid fa-comments mr-2', max_length=255),
        ),
    ]
